### ISSUE TITLE
Is it truly async ?

### ISSUE THREAD

**Issue by foremtehan** [badfarm/zanzara#49]
Hey badfram, Thanks for your work.

I cant understand one thing in zanzara, Let me describe, I put some delay on the script to see if its truly an async or not :

```php
$bot = new Zanzara("YOUR-BOT-TOKEN");

$bot->onCommand('start', function (Context $ctx) {
    sleep(15);
    $ctx->sendMessage('Hello');
});

$bot->run();
```

I send `/start` with two separate account at the same time, Bot zanzara finished the updates in 30 seconds instead of 15, It responded one by one, Shouldn't it take the request and pass it to the event loop and ready for next request?  Am i missing something ?

**Comment by cheeghi** [comment]
Hi, thank you for your question!

When a new update comes from Telegram, the `event loop` processes the request. The request is Zanzara that parses the update and, in turn, calls the listeners you have defined (onCommand in your case).
It doesn't "take the request and pass it to the event loop", `Zanzara is within the event loop`.
Being in the event loop means that you `can't do anything that blocks the loop` (eg. calling the *sleep()* function), otherwise you are preventing any other request from being processed.

Every I/O operation must be performed through callbacks which don't block the loop. Keep in mind that many php libraries are blocking by default (PDO, Guzzle, etc.). That's the reason why non-blocking correspondent libraries exist in order to perform such operations.

I hope I was clear enough.
