### ISSUE TITLE
banChatSenderChat

### ISSUE THREAD

**Issue by j3XeZ** [badfarm/zanzara#55]
Hey!
The banChatSenderChat method does not work. I specify the parameters correctly, I even tried it stupidly, the user can still send a message from the channels, also some error occurs on this method, but I cannot see it.
       
Example: 
$target = $ctx->getMessage()->getChat()->getId();
$senderChat = $ctx->getMessage()->getSenderChat()->getId();
$ctx->banChatSenderChat($target,$senderChat);

**Comment by cheeghi** [comment]
Hi, if the method call fails, you should see an error message on the console. Otherwise it means the call was successful.
Can you try making the call through a browser and check the result?
`https://api.telegram.org/bot<YOUR_BOT_TOKEN>/banChatSenderChat?chat_id=<CHAT_ID>&sender_chat_id=<SENDER_CHAT_ID>`
Thanks
