### ISSUE TITLE
How to use  WyriHaximus / reactphp-psr-3-loggly

### ISSUE THREAD

**Issue by evanh-shumakov** [badfarm/zanzara#81]
Never use something with ReactPHP before. There is a tip in Zanzara project to use [WyriHaximus/reactphp-psr-3-loggly](https://github.com/WyriHaximus/reactphp-psr-3-loggly) logger. But I don't get how to use it. Would anyone gave me any code snippet please.

**Comment by awohsen** [comment]
https://github.com/badfarm/zanzara/blob/8c2e4432d4d252a8db94ddb43990ff71d10965bb/tests/Telegram/TestTelegram.php#L165

I'm assuming it's because in asynchronous projects, the more your operations are done in async, the overall faster your app is.
And I'm also assuming that Loggly is a cloud-based log management service provider and [WyriHaximus/reactphp-psr-3-loggly](https://github.com/WyriHaximus/reactphp-psr-3-loggly) is just an async client for it which makes it good choice for really big projects. 

I personally think its an overkill for simple projects like simple telegram bots but this is how you implement it:
```php
<?php

use React\EventLoop\Loop;
use WyriHaximus\React\PSR3\Loggly\LogglyLogger;
use Zanzara\Config;
use Zanzara\Zanzara;

$token = 'loggly token';
$loop = Loop::get();
$logger = LogglyLogger::create($loop, $token);

$config = new Config();
$config->setLoop($loop);
$config->setLogger($logger);

$bot = new Zanzara($_ENV['BOT_TOKEN'], $config);

$bot->run();
```

if you prefer [Seldaek/monolog](https://github.com/Seldaek/monolog) you can use:
```php
<?php

use Monolog\{Logger, Handler\StreamHandler};
use Zanzara\Config;
use Zanzara\Zanzara;

$logger = new Logger('name');
$logger->pushHandler(new StreamHandler(__DIR__ . '/logs/'.date("Y-m-d").'.log', Logger::DEBUG));

$config = new Config();
$config->setLogger($logger);

$bot = new Zanzara($_ENV['BOT_TOKEN'], $config);

$bot->run();
```

**Comment by evanh-shumakov** [comment]
@awohsen So, am I've got it right: the "loggly token" is a token from cloud service, and I should create an account firstly?

**Comment by awohsen** [comment]
> @awohsen thank you so much! I've just got it wrong. I thought, that I have to use [WyriHaximus/reactphp-psr-3-loggly](https://github.com/WyriHaximus/reactphp-psr-3-loggly), but now I understand, that it's just an advice, and I can use Monolog.

exactly, also if you want to use your log interface, you can pass the $logger variable with 'use  ($logger)' to your anonymous function or create a custom context class that has: 
 ```php
<?php

use Zanzara\ZanzaraLogger;
use Zanzara\Telegram\Type\Update;
use Psr\Container\ContainerInterface;

class Context extends \Zanzara\Context
{

    /**
     * @var ZanzaraLogger
     */
    protected ZanzaraLogger $logger;

    function __construct(Update $update, ContainerInterface $container)
    {
        parent::__construct($update, $container);

        $this->logger = $container->get(ZanzaraLogger::class);
        
    }

    /**
     * @return ZanzaraLogger
     */
    public function log(): ZanzaraLogger
    {
        return $this->logger;
    }

}
```

don't forget to provide it in zanzara config: 
```php
...

$config = new Config();
$config->setLogger($logger);
$config->setContextClass(Context::class);

$bot = new Zanzara($_ENV['BOT_TOKEN'], $config);

...
