### ISSUE TITLE
getUpdateType() Errors

### ISSUE THREAD

**Issue by mdurao** [badfarm/zanzara#92]
Hi there,

is this code still being updated?

Have an error in my logs:

`Failed to process Telegram update , reason: TypeError: Zanzara\Telegram\Type\Update::getUpdateType(): Return value must be of type string, null`

Searching the issues, looks like some new kind of event that the code is not recognizing.

What can I do to mitigate this errors or just hide them, since they look like false-positives?

Thank you,

**Comment by awohsen** [comment]
Hi, it seems new telegram-api update has came out with new update type which zanzara can't recognize it. 

If your project has nothing to do with that update type you can just ignore it, also by using `$config->setDisableZanzaraLogger()` you can hide all zanzara logs too (or w/ addition of using custom logger).

**Comment by mdurao** [comment]
Hi @awohsen , ty for you reply.

Will try to disable the logger then...

Do you know if this project is still being updated or if there is any alternative?

Thanks

**Comment by awohsen** [comment]
> Do you know if this project is still being updated or if there is any alternative?

Well, there's not much people interested in keeping this library updated but me, since i've used it in too many production projects, its hard for me to switch to another library now. 
However there's similar approach which its  usage is kinda similar called [Nutgram](https://github.com/nutgram/nutgram) which you might wanna try out.

Still as i said there's no breaking change rn that could make zanzara unusable its just few new api methods and update types which in worst case you can use via call api anyway.
